[package]
name = "test-cc-taxii2-client-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc-taxii2-client-rs = { path = "../.." }
dotenv = "0.15"
