name: Lint Build Deploy

on: push

env:
  CARGO_TERM_COLOR: always

jobs:

  test:
    environment: Testing
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: cargo clippy --workspace --verbose
    - name: Test
      env:
        TAXII_USERNAME: ${{ secrets.TAXII_USERNAME }}
        TAXII_API_KEY: ${{ secrets.TAXII_API_KEY }}
      run: cargo test --release --tests --workspace --verbose

  build:
    environment: Testing
    needs:
      - test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose


  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    environment: Deploy
    needs:
    - build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Deploy
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish --verbose
