name: Lint Build Deploy

on: push

env:
  CARGO_TERM_COLOR: always

jobs:

  test:
    environment: Testing
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: cargo clippy --verbose
    - name: Test
      env:
        TAXII_USERNAME: ${{ secrets.TAXII_USERNAME }}
        TAXII_API_KEY: ${{ secrets.TAXII_API_KEY }}
      run: cargo test --all-features --release --lib --tests --verbose

  build:
    environment: Testing
    needs:
      - test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose


  deploy:
    environment: Deploy
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      env:
        CARGO_REGISTRY_TOKEN ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo build --release --verbose


